sudo: false
language: node_js

# https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#specifying-nodejs-versions
node_js:
  - "node" # latest stable Node.js release
  - "lts/*" # latest LTS Node.js release

before_script:
  - npm install

script:
  - npm run test
  - npm run build

# https://docs.travis-ci.com/user/notifications/#Notifications
# notifications:
#   email:
#     - john.doe@example.com
