name: CI
on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [12.x, 13.x, 14.x]

    env:
      CI: true

    steps:
    - name: Checkout
      # https://github.com/actions/checkout/releases/tag/v2.3.4
      uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f

    - name: Use Node.js ${{ matrix.node-version }}
      # https://github.com/actions/setup-node/releases/tag/v2.1.4
      uses: actions/setup-node@c46424eee26de4078d34105d3de3cc4992202b1e
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: |
        npm install

    - name: Test and build
      run: |
        npm test
        npm run build
